events:
- channel: C073PA08MQA
  end: '2024-05-17'
  name: Outernet
  start: '2024-05-15'
  timezone: America/New_York
  users:
  - flights:
    - code: DL2796
      date: '2024-05-15'
    - code: WN4727
      date: '2024-05-15'
    id: U04CBLNSVH6
    name: David
version: 1
